version: 2.1

orbs:
  docker: circleci/docker@1.7.0

jobs:
  check:
    # by default, this is using the legacy circleci/python:3.6 image
    executor: docker/docker
    steps:
      - run:
          name: Confirm docker CLI is available
          command: |
            # we should already have Docker installed
            command -v docker
      - setup_remote_docker
      - run:
          name: Check Docker version
            # print Docker version (this expects our Docker server/daemon is up)
            docker version

workflows:
  main:
    jobs:
      - check
